# SPDX-FileCopyrightText: 2021-2022 The Ikarus Developers mueller@ibb.uni-stuttgart.de
# SPDX-License-Identifier: CC0-1.0
component_depth: 4
languages:
- name: cpp
  production:
    include:
      - /ikarus/.*\.cpp
      - /ikarus/.*\.h
    exclude:
      - /tests/.*\.cpp
  test:
    include:
      - /tests/.*\.cpp
