// SPDX-FileCopyrightText: 2022 The Ikarus Developers mueller@ibb.uni-stuttgart.de
// SPDX-License-Identifier: LGPL-3.0-or-later

Module: ikarus
Version: 0.2
Maintainer: mueller@ibb.uni-stuttgart.de
Depends: dune-typetree dune-geometry dune-iga dune-localfefunctions dune-functions dune-grid dune-fufem dune-alugrid dune-foamgrid dune-uggrid dune-vtk
Python-Requires: pip>=21.a portalocker numpy wheel setuptools>=41 jinja2
# Optional build dependencies
#Suggests:
