// SPDX-FileCopyrightText: 2021-2023 The Ikarus Developers mueller@ibb.uni-stuttgart.de
// SPDX-License-Identifier: LGPL-3.0-or-later

Module: ikarus
Version: 0.3.6
Maintainer: mueller@ibb.uni-stuttgart.de
Python-Requires: matplotlib scipy numpy dune-common dune-grid dune-geometry  dune-istl dune-functions
Depends: dune-common dune-grid dune-geometry  dune-istl
Suggests: dune-uggrid dune-iga  dune-alugrid dune-foamgrid dune-vtk dune-typetree dune-localfefunctions dune-fufem
# Optional build dependencies
