FROM ubuntu:hirsute

ENV HOME /root
ENV DEBIAN_FRONTEND "noninteractive"

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get -y install \
        build-essential \
        libssl-dev \
        git \
        wget \
        apt-utils \
        software-properties-common \
        gfortran \
        gcc-11 \
        g++-11 \
        clang \
        liblapack-dev \
        libblas-dev \
        libsuitesparse-dev \
        libdune-common-dev \
        libdune-geometry-dev \
        libdune-grid-dev \
        libspdlog-dev \
        libbenchmark-dev \
        libgtest-dev && \
        cd /usr/src/googletest && \
        cmake . && \
        cmake --build . --target install && \
        cd ~/ && \
        git clone https://gitlab.com/libeigen/eigen.git && \
        cd eigen && \
        git checkout 3.4 && \
        ls && \
        mkdir build && \
        cd build && \
        cmake ../ && \
        sudo make install && \
        ls && \
        cd .. && \
        ls && \
        cd .. && \
        ls && \
        rm -r eigen && \
        git clone https://github.com/alandefreitas/matplotplusplus.git && \
        cd matplotplusplus && \
        mkdir -p build && \
        cd build && \
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF && \
        cmake --build . --parallel 4 --config Release && \
        cmake --install . && \
        cd ../.. && \
        rm -r matplotplusplus
CMD [ "/bin/bash" ]

WORKDIR $HOME