FROM debian:bookworm

ENV HOME /root
ENV DEBIAN_FRONTEND "noninteractive"
ENV CI true

RUN apt-get update -q -y && apt-get upgrade -y && \
    apt-get -y install --no-install-recommends \
        build-essential \
        libssl-dev \
        git \
        wget \
        apt-utils \
        software-properties-common \
        gfortran \
        gcc-11 \
        g++-11 \
        gcovr \
        clang \
        clang-tidy \
                libclang-13-dev \
                libc++-13-dev \
                libc++abi-13-dev \
                llvm-13-dev \
        liblapack-dev \
        libblas-dev \
        libsuitesparse-dev \
        libdune-common-dev \
        libdune-geometry-dev \
        libdune-grid-dev \
        libspdlog-dev \
        libbenchmark-dev \
        libgtest-dev \
        gnuplot \
        gnuplot-x11 \
        curl \
        cppcheck && \
        mkdir -p iwyu && \
        cd iwyu && \
        git clone https://github.com/include-what-you-use/include-what-you-use.git && \
        cd include-what-you-use && \
        git checkout clang_13 && \
        cd .. && \
        mkdir -p build && cd build && \
        cmake -G "Unix Makefiles" -DIWYU_LLVM_ROOT_PATH=/usr/lib/llvm-13 ../include-what-you-use && \
        make && \
        make install && \
        cd /usr/src/googletest && \
        cmake . && \
        cmake --build . --target install && \
        cd ~/ && \
        git clone https://gitlab.com/libeigen/eigen.git && \
        cd eigen && \
        git checkout 3.4 && \
        ls && \
        mkdir build && \
        cd build && \
        cmake ../ && \
        make install && \
        ls && \
        cd .. && \
        ls && \
        cd .. && \
        ls && \
        rm -r eigen && \
        git clone https://github.com/alandefreitas/matplotplusplus.git && \
        cd matplotplusplus && \
        mkdir -p build && \
        cd build && \
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF && \
        cmake --build . --parallel 4 --config Release && \
        cmake --install . && \
        cd ../.. && \
        rm -r matplotplusplus && \
        apt-get auto-remove -y && \
        apt-get clean && \
        rm -rvf /var/lib/apt/lists/* && \
        rm -rvf /var/cache/apt/archives/* && \
        apt-get -y remove  \
        software-properties-common
CMD [ "/bin/bash" ]

WORKDIR $HOME
