FROM mcr.microsoft.com/windows/nanoserver:1909-amd64


# Restore the default Windows shell for correct batch processing below.
SHELL ["cmd", "/S", "/C"]
ENV global:progressPreference 'silentlyContinue'

RUN powershell.exe -Command \
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
    iex ((New-Object System.Net.WebClient).DownloadString('http://chocolatey.org/install.ps1'))

#install 7z
RUN powershell.exe -Command \
    choco install -y 7zip.install --no-progress; \
    choco install -y choco-cleaner --no-progress; \
    choco install -y git --no-progress; \
    choco install -y cmake --no-progress; \
    choco-cleaner.bat; \
    choco uninstall choco-cleaner -x -y; \
    cd C:; \
    mkdir winlibs; \
    Invoke-WebRequest -Uri https://github.com/brechtsanders/winlibs_mingw/releases/download/11.1.0-12.0.0-9.0.0-r2/winlibs-x86_64-posix-seh-gcc-11.1.0-llvm-12.0.0-mingw-w64-9.0.0-r2.7z -OutFile winlibs/libs.7z; \
    cd winlibs; \
    7z x libs.7z; \
    rm libs.7z; \
    setx path "%path%;C:\winlibs\mingw64\bin"; \ 
    cd C:; \
    mkdir Ikarus_Dependencies; \
    Invoke-WebRequest -Uri https://github.com/rath3t/IkarusDependencies/releases/download/v0.3/Dependencies_release.7z -OutFile Ikarus_Dependencies/dependencies.7z; \
    cd Ikarus_Dependencies; \
    7z x dependencies.7z; \
    rm dependencies.7z


# Default to PowerShell if no other command specified.
ENTRYPOINT ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
