am:
  name: Alexander Müller
  description: Ikarus maintainer
  avatar: https://avatars.githubusercontent.com/u/10537464?v=4

tm:
  name: Tarun Kumar Mitruka Vinod Kumar Mitruka
  description: Ikarus maintainer
  avatar: https://avatars.githubusercontent.com/u/92575489?v=4