# SPDX-FileCopyrightText: 2022 The Ikarus Developers mueller@ibb.uni-stuttgart.de
# SPDX-License-Identifier: CC0-1.0

name: Publish Python  distributions to TestPyPI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/ghpages.yml'
      - '.github/workflows/createDockerContainer.yml'
      - '**.md'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    container:
      image: ikarusproject/ikarus-dev:latest
      options: --memory-swap="20g" --memory="20g" --cpus="2" --user root

    steps:
      - uses: actions/checkout@v3
      - name: Install twine and scikit-build
        run: |
          /dune/dune-common/build-cmake/run-in-dune-env pip install twine scikit-build
      - name: Build a binary wheel and a source tarball
        run: |
          /dune/dune-common/build-cmake/run-in-dune-env python setup.py sdist


      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TESTPYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
